### ISSUE TITLE
It also support huawei ax3 pro router,but still have some errors.

### ISSUE THREAD

**Issue by ruicai83** [juacas/honor_x3#1]
Hi,

Thanks for your works, I have a huawei ax3 pro router, and i try ur integrtion, fortunately, it also work.
device tracker can fetch the device info immediately,and all the device have a right state.

**Issue:**

But sometimes, all the devices state will change to "not home", actually the device never leave home. After a few minutes, the device state  change to "home", I also login to the router to check that the device have never lost  from the router. 

**And the homeassistant log is :**

Logger: custom_components.honor_x3.device_tracker
Source: custom_components/honor_x3/device_tracker.py:50
Integration: Honor 3/X3 Router ([documentation](https://raw.githubusercontent.com/juacas/honor_x3/master/README.md), [issues](https://github.com/juacas/honor_x3/issues))
First occurred: 2022年3月2日 24:45:26 (5128 occurrences)
Last logged: 24:34:03

Can't update device list

Logger: custom_components.honor_x3.device_tracker
Source: custom_components/honor_x3/device_tracker.py:99
Integration: Honor 3/X3 Router ([documentation](https://raw.githubusercontent.com/juacas/honor_x3/master/README.md), [issues](https://github.com/juacas/honor_x3/issues))
First occurred: 2022年3月2日 24:45:26 (5128 occurrences)
Last logged: 24:34:03

Login failed: admin:xxxxxx@192.168.3.1

Logger: custom_components.honor_x3.honorx3client.honor_x3_client
Source: custom_components/honor_x3/honorx3client/honor_x3_client.py:101
Integration: Honor 3/X3 Router ([documentation](https://raw.githubusercontent.com/juacas/honor_x3/master/README.md), [issues](https://github.com/juacas/honor_x3/issues))
First occurred: 2022年3月2日 24:45:26 (5128 occurrences)
Last logged: 24:34:03

Failed to login: 'salt'
Failed to login: 'err'
Failed to login: HTTPSConnectionPool(host='192.168.3.1', port=443): Pool is closed.

Thanks again!

**Comment by juacas** [comment]
Hello,
I've seen this errors when there is another session opened in a browser. This router does not allow simultaneous logins to the administrative webpage.
Is it possible that you have an opened session in a tab of your browser, another device or from the Hilink App?

**Comment by ruicai83** [comment]
Thanks for your reply.
maybe the wrong setting(  interval_seconds: 3) cause this issue.
After set  the  interval_seconds to 10, the warning and error disappear.
