### ISSUE TITLE
Posibility to add more features togheter

### ISSUE THREAD

**Issue by txitxo0** [juacas/honor_x3#2]
Hi there @juacas I am not opening an issue, I was just wondering if you are open to add more features to this component trying to get i.e. guests wifi switch or port forwarding, and others.

I am trying to understand the login authentication to be able to add it through these other projects:
- https://gist.github.com/fpasteau/01d05f688079b00be7d014d01fef0dd6
- https://github.com/siphomateke/huawei-router-api

**Comment by juacas** [comment]
Sorry, but I'm no longer using this router.

However, the login process is implemented in this project: https://github.com/juacas/honor_x3/blob/379895368148fa19b4390a02ff902d4a1c6e1cea/custom_components/honor_x3/honorx3client/honor_x3_client.py#L47 and it is pretty readable IMHO.

**Comment by juacas** [comment]
Of course, you are kindly invited to join this project and contribute with new features.

**Comment by txitxo0** [comment]
> Of course, you are kindly invited to join this project and contribute with new features.

I will try then :) let's see what I get
